language: ruby

addons:
  apt:
    packages:
      - fonts-lmodern
      - make

install:
  - ./install.sh

script:
  - export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
  - make
  - mkdir -p pdf
  - mv talk.pdf pdf/

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
    - $HOME/.fonts

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: pdf
  on:
    branch: master
