language: ruby
sudo: required

addons:
  apt:
    packages:
      - latexmk
      - make
      - texlive-fonts-extra
      - texlive-fonts-recommended
      - texlive-generic-extra
      - texlive-latex-extra
      - texlive-math-extra
      - texlive-pictures
      - texlive-science
      - texlive-xetex

before_install:
  - wget https://github.com/matze/mtheme/archive/master.zip
  - unzip master.zip
  - (cd mtheme-master && make sty && make install)
  - .ci/fira.sh

script:
  - make
  - mkdir -p pdf
  - mv talk.pdf pdf/

branches:
  only:
  - master

deploy:
  edge:
    branch: v1.8.47
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: pdf
  on:
    branch: master
