language: ruby
sudo: required

addons:
  sources:
    - sourceline: 'ppa:jonathonf/texlive'
  apt:
    packages:
      - fonts-lmodern
      - latex-beamer
      - latex-xcolor
      - latexmk
      - make
      - texlive-full
      - texlive-xetex

before_install:
  ## Install Fira Fonts
  - wget -q https://github.com/mozilla/Fira/archive/4.202.zip
  - unzip -qq 4.202.zip
  - mkdir -p $HOME/.fonts
  - cp Fira*/otf/Fira* $HOME/.fonts

  ## Install Metropolis theme
  - wget -q https://github.com/matze/mtheme/archive/master.zip
  - unzip -qq master.zip
  - (cd mtheme-master && make sty && make install)

script:
  - make
  - mkdir -p pdf
  - mv talk.pdf pdf/

branches:
  only:
  - master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: pdf
  on:
    branch: master

cache:
  apt: true
