language: ruby
sudo: required

before_install:
  - ./install.sh


script:
  - make
  - mkdir -p pdf
  - mv talk.pdf pdf/

branches:
  only:
  - master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: pdf
  on:
    branch: master
