language: ruby
sudo: required

addons:
  apt:
    packages:
      - fonts-lmodern
      - latex-beamer
      - latex-xcolor
      - latexmk
      - make
      - texlive-fonts-extra
      - texlive-fonts-recommended
      - texlive-generic-extra
      - texlive-latex-extra
      - texlive-math-extra
      - texlive-pictures
      - texlive-science
      - texlive-xetex

before_install:
  ## Install Dependencies
  - ./install.sh


script:
  - make
  - mkdir -p pdf
  - mv talk.pdf pdf/

branches:
  only:
  - master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: pdf
  on:
    branch: master
